### ISSUE TITLE
Rotate screen

### ISSUE THREAD

**Issue by colesnicov** [Fonger/ESP8266-RTOS-SSD1306#5]
Hello. Rotate screen to 180 degrees?

**Comment by 0x0aa** [comment]
The SSD1306 is initialized with:

ssd1306_set_segment_remapping_enabled(dev, **false**)
ssd1306_set_scan_direction_fwd(dev, **true**)

Invert those booleans and the resulting image will be flipped and mirrored.

**Comment by colesnicov** [comment]
Ok.  Got it:

```
ssd1306_set_segment_remapping_enabled(dev, true);

ssd1306_set_scan_direction_fwd(dev, false);

```

It's work..
